# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-12 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearskies_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airfield',
            name='metarstation',
            field=models.BooleanField(default=False),
        ),
    ]
