# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-12 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearskies_app', '0002_airfield_metarstation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airfield',
            name='metarstation',
        ),
        migrations.AddField(
            model_name='airfield',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='airfield',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
